name: Ruff Code Formatter and Linting Check

"on":
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: Ruff Format and Lint Check
        uses: chartboost/ruff-action@v1
        with:
          changed-files: 'true'
